# Generated by Django 3.2.7 on 2023-09-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_operations', '0002_auto_20230912_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='title',
        ),
    ]
